# Generated by Django 4.1.3 on 2022-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multiuser',
            name='is_labour',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='multiuser',
            name='is_manager',
            field=models.BooleanField(null=True),
        ),
    ]
